language: generic 

#sudo: required
services:
  - docker

before_install:
  - docker build -t ahmoud2/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ahmoud2/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "northeast-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-144418194253"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_Access_key_ID
  secret_access_key: "$AWS_Secret_access_key"